DROP TABLE IF EXISTS clickhouse.dwh.fact_sales;
DROP TABLE IF EXISTS clickhouse.dwh.dim_date;
DROP TABLE IF EXISTS clickhouse.dwh.dim_customer;
DROP TABLE IF EXISTS clickhouse.dwh.dim_product;
DROP TABLE IF EXISTS clickhouse.dwh.dim_store;
DROP TABLE IF EXISTS clickhouse.dwh.dim_supplier;

CREATE TABLE clickhouse.dwh.dim_date AS
WITH unified_source AS (
    SELECT
        CAST(id AS varchar) AS id,
        CAST(customer_first_name AS varchar) AS customer_first_name,
        CAST(customer_last_name AS varchar) AS customer_last_name,
        CAST(customer_age AS varchar) AS customer_age,
        CAST(customer_email AS varchar) AS customer_email,
        CAST(customer_country AS varchar) AS customer_country,
        CAST(customer_postal_code AS varchar) AS customer_postal_code,
        CAST(customer_pet_type AS varchar) AS customer_pet_type,
        CAST(customer_pet_name AS varchar) AS customer_pet_name,
        CAST(customer_pet_breed AS varchar) AS customer_pet_breed,
        CAST(seller_first_name AS varchar) AS seller_first_name,
        CAST(seller_last_name AS varchar) AS seller_last_name,
        CAST(seller_email AS varchar) AS seller_email,
        CAST(seller_country AS varchar) AS seller_country,
        CAST(seller_postal_code AS varchar) AS seller_postal_code,
        CAST(product_name AS varchar) AS product_name,
        CAST(product_category AS varchar) AS product_category,
        CAST(product_price AS varchar) AS product_price,
        CAST(product_quantity AS varchar) AS product_quantity,
        CAST(sale_date AS varchar) AS sale_date,
        CAST(sale_customer_id AS varchar) AS sale_customer_id,
        CAST(sale_seller_id AS varchar) AS sale_seller_id,
        CAST(sale_product_id AS varchar) AS sale_product_id,
        CAST(sale_quantity AS varchar) AS sale_quantity,
        CAST(sale_total_price AS varchar) AS sale_total_price,
        CAST(store_name AS varchar) AS store_name,
        CAST(store_location AS varchar) AS store_location,
        CAST(store_city AS varchar) AS store_city,
        CAST(store_state AS varchar) AS store_state,
        CAST(store_country AS varchar) AS store_country,
        CAST(store_phone AS varchar) AS store_phone,
        CAST(store_email AS varchar) AS store_email,
        CAST(pet_category AS varchar) AS pet_category,
        CAST(product_weight AS varchar) AS product_weight,
        CAST(product_color AS varchar) AS product_color,
        CAST(product_size AS varchar) AS product_size,
        CAST(product_brand AS varchar) AS product_brand,
        CAST(product_material AS varchar) AS product_material,
        CAST(product_description AS varchar) AS product_description,
        CAST(product_rating AS varchar) AS product_rating,
        CAST(product_reviews AS varchar) AS product_reviews,
        CAST(product_release_date AS varchar) AS product_release_date,
        CAST(product_expiry_date AS varchar) AS product_expiry_date,
        CAST(supplier_name AS varchar) AS supplier_name,
        CAST(supplier_contact AS varchar) AS supplier_contact,
        CAST(supplier_email AS varchar) AS supplier_email,
        CAST(supplier_phone AS varchar) AS supplier_phone,
        CAST(supplier_address AS varchar) AS supplier_address,
        CAST(supplier_city AS varchar) AS supplier_city,
        CAST(supplier_country AS varchar) AS supplier_country
    FROM postgres.raw.mock_data
    UNION ALL
    SELECT
        CAST(id AS varchar) AS id,
        CAST(customer_first_name AS varchar) AS customer_first_name,
        CAST(customer_last_name AS varchar) AS customer_last_name,
        CAST(customer_age AS varchar) AS customer_age,
        CAST(customer_email AS varchar) AS customer_email,
        CAST(customer_country AS varchar) AS customer_country,
        CAST(customer_postal_code AS varchar) AS customer_postal_code,
        CAST(customer_pet_type AS varchar) AS customer_pet_type,
        CAST(customer_pet_name AS varchar) AS customer_pet_name,
        CAST(customer_pet_breed AS varchar) AS customer_pet_breed,
        CAST(seller_first_name AS varchar) AS seller_first_name,
        CAST(seller_last_name AS varchar) AS seller_last_name,
        CAST(seller_email AS varchar) AS seller_email,
        CAST(seller_country AS varchar) AS seller_country,
        CAST(seller_postal_code AS varchar) AS seller_postal_code,
        CAST(product_name AS varchar) AS product_name,
        CAST(product_category AS varchar) AS product_category,
        CAST(product_price AS varchar) AS product_price,
        CAST(product_quantity AS varchar) AS product_quantity,
        CAST(sale_date AS varchar) AS sale_date,
        CAST(sale_customer_id AS varchar) AS sale_customer_id,
        CAST(sale_seller_id AS varchar) AS sale_seller_id,
        CAST(sale_product_id AS varchar) AS sale_product_id,
        CAST(sale_quantity AS varchar) AS sale_quantity,
        CAST(sale_total_price AS varchar) AS sale_total_price,
        CAST(store_name AS varchar) AS store_name,
        CAST(store_location AS varchar) AS store_location,
        CAST(store_city AS varchar) AS store_city,
        CAST(store_state AS varchar) AS store_state,
        CAST(store_country AS varchar) AS store_country,
        CAST(store_phone AS varchar) AS store_phone,
        CAST(store_email AS varchar) AS store_email,
        CAST(pet_category AS varchar) AS pet_category,
        CAST(product_weight AS varchar) AS product_weight,
        CAST(product_color AS varchar) AS product_color,
        CAST(product_size AS varchar) AS product_size,
        CAST(product_brand AS varchar) AS product_brand,
        CAST(product_material AS varchar) AS product_material,
        CAST(product_description AS varchar) AS product_description,
        CAST(product_rating AS varchar) AS product_rating,
        CAST(product_reviews AS varchar) AS product_reviews,
        CAST(product_release_date AS varchar) AS product_release_date,
        CAST(product_expiry_date AS varchar) AS product_expiry_date,
        CAST(supplier_name AS varchar) AS supplier_name,
        CAST(supplier_contact AS varchar) AS supplier_contact,
        CAST(supplier_email AS varchar) AS supplier_email,
        CAST(supplier_phone AS varchar) AS supplier_phone,
        CAST(supplier_address AS varchar) AS supplier_address,
        CAST(supplier_city AS varchar) AS supplier_city,
        CAST(supplier_country AS varchar) AS supplier_country
    FROM clickhouse.raw.mock_data
),
dates AS (
    SELECT DISTINCT TRY(CAST(date_parse(sale_date, '%c/%e/%Y') AS date)) AS full_date
    FROM unified_source
    WHERE sale_date IS NOT NULL
)
SELECT
    CAST(date_format(full_date, '%Y%m%d') AS bigint) AS date_id,
    full_date,
    year(full_date) AS year_num,
    month(full_date) AS month_num,
    day(full_date) AS day_num,
    quarter(full_date) AS quarter_num
FROM dates
WHERE full_date IS NOT NULL;

CREATE TABLE clickhouse.dwh.dim_customer AS
WITH unified_source AS (
    SELECT
        CAST(id AS varchar) AS id,
        CAST(customer_first_name AS varchar) AS customer_first_name,
        CAST(customer_last_name AS varchar) AS customer_last_name,
        CAST(customer_age AS varchar) AS customer_age,
        CAST(customer_email AS varchar) AS customer_email,
        CAST(customer_country AS varchar) AS customer_country,
        CAST(customer_postal_code AS varchar) AS customer_postal_code,
        CAST(customer_pet_type AS varchar) AS customer_pet_type,
        CAST(customer_pet_name AS varchar) AS customer_pet_name,
        CAST(customer_pet_breed AS varchar) AS customer_pet_breed,
        CAST(seller_first_name AS varchar) AS seller_first_name,
        CAST(seller_last_name AS varchar) AS seller_last_name,
        CAST(seller_email AS varchar) AS seller_email,
        CAST(seller_country AS varchar) AS seller_country,
        CAST(seller_postal_code AS varchar) AS seller_postal_code,
        CAST(product_name AS varchar) AS product_name,
        CAST(product_category AS varchar) AS product_category,
        CAST(product_price AS varchar) AS product_price,
        CAST(product_quantity AS varchar) AS product_quantity,
        CAST(sale_date AS varchar) AS sale_date,
        CAST(sale_customer_id AS varchar) AS sale_customer_id,
        CAST(sale_seller_id AS varchar) AS sale_seller_id,
        CAST(sale_product_id AS varchar) AS sale_product_id,
        CAST(sale_quantity AS varchar) AS sale_quantity,
        CAST(sale_total_price AS varchar) AS sale_total_price,
        CAST(store_name AS varchar) AS store_name,
        CAST(store_location AS varchar) AS store_location,
        CAST(store_city AS varchar) AS store_city,
        CAST(store_state AS varchar) AS store_state,
        CAST(store_country AS varchar) AS store_country,
        CAST(store_phone AS varchar) AS store_phone,
        CAST(store_email AS varchar) AS store_email,
        CAST(pet_category AS varchar) AS pet_category,
        CAST(product_weight AS varchar) AS product_weight,
        CAST(product_color AS varchar) AS product_color,
        CAST(product_size AS varchar) AS product_size,
        CAST(product_brand AS varchar) AS product_brand,
        CAST(product_material AS varchar) AS product_material,
        CAST(product_description AS varchar) AS product_description,
        CAST(product_rating AS varchar) AS product_rating,
        CAST(product_reviews AS varchar) AS product_reviews,
        CAST(product_release_date AS varchar) AS product_release_date,
        CAST(product_expiry_date AS varchar) AS product_expiry_date,
        CAST(supplier_name AS varchar) AS supplier_name,
        CAST(supplier_contact AS varchar) AS supplier_contact,
        CAST(supplier_email AS varchar) AS supplier_email,
        CAST(supplier_phone AS varchar) AS supplier_phone,
        CAST(supplier_address AS varchar) AS supplier_address,
        CAST(supplier_city AS varchar) AS supplier_city,
        CAST(supplier_country AS varchar) AS supplier_country
    FROM postgres.raw.mock_data
    UNION ALL
    SELECT
        CAST(id AS varchar) AS id,
        CAST(customer_first_name AS varchar) AS customer_first_name,
        CAST(customer_last_name AS varchar) AS customer_last_name,
        CAST(customer_age AS varchar) AS customer_age,
        CAST(customer_email AS varchar) AS customer_email,
        CAST(customer_country AS varchar) AS customer_country,
        CAST(customer_postal_code AS varchar) AS customer_postal_code,
        CAST(customer_pet_type AS varchar) AS customer_pet_type,
        CAST(customer_pet_name AS varchar) AS customer_pet_name,
        CAST(customer_pet_breed AS varchar) AS customer_pet_breed,
        CAST(seller_first_name AS varchar) AS seller_first_name,
        CAST(seller_last_name AS varchar) AS seller_last_name,
        CAST(seller_email AS varchar) AS seller_email,
        CAST(seller_country AS varchar) AS seller_country,
        CAST(seller_postal_code AS varchar) AS seller_postal_code,
        CAST(product_name AS varchar) AS product_name,
        CAST(product_category AS varchar) AS product_category,
        CAST(product_price AS varchar) AS product_price,
        CAST(product_quantity AS varchar) AS product_quantity,
        CAST(sale_date AS varchar) AS sale_date,
        CAST(sale_customer_id AS varchar) AS sale_customer_id,
        CAST(sale_seller_id AS varchar) AS sale_seller_id,
        CAST(sale_product_id AS varchar) AS sale_product_id,
        CAST(sale_quantity AS varchar) AS sale_quantity,
        CAST(sale_total_price AS varchar) AS sale_total_price,
        CAST(store_name AS varchar) AS store_name,
        CAST(store_location AS varchar) AS store_location,
        CAST(store_city AS varchar) AS store_city,
        CAST(store_state AS varchar) AS store_state,
        CAST(store_country AS varchar) AS store_country,
        CAST(store_phone AS varchar) AS store_phone,
        CAST(store_email AS varchar) AS store_email,
        CAST(pet_category AS varchar) AS pet_category,
        CAST(product_weight AS varchar) AS product_weight,
        CAST(product_color AS varchar) AS product_color,
        CAST(product_size AS varchar) AS product_size,
        CAST(product_brand AS varchar) AS product_brand,
        CAST(product_material AS varchar) AS product_material,
        CAST(product_description AS varchar) AS product_description,
        CAST(product_rating AS varchar) AS product_rating,
        CAST(product_reviews AS varchar) AS product_reviews,
        CAST(product_release_date AS varchar) AS product_release_date,
        CAST(product_expiry_date AS varchar) AS product_expiry_date,
        CAST(supplier_name AS varchar) AS supplier_name,
        CAST(supplier_contact AS varchar) AS supplier_contact,
        CAST(supplier_email AS varchar) AS supplier_email,
        CAST(supplier_phone AS varchar) AS supplier_phone,
        CAST(supplier_address AS varchar) AS supplier_address,
        CAST(supplier_city AS varchar) AS supplier_city,
        CAST(supplier_country AS varchar) AS supplier_country
    FROM clickhouse.raw.mock_data
)
SELECT DISTINCT
    TRY_CAST(sale_customer_id AS bigint) AS customer_id,
    NULLIF(TRIM(customer_first_name), '') AS customer_first_name,
    NULLIF(TRIM(customer_last_name), '') AS customer_last_name,
    NULLIF(TRIM(customer_email), '') AS customer_email,
    TRY_CAST(customer_age AS integer) AS customer_age,
    NULLIF(TRIM(customer_country), '') AS customer_country,
    NULLIF(TRIM(customer_postal_code), '') AS customer_postal_code,
    NULLIF(TRIM(customer_pet_type), '') AS customer_pet_type,
    NULLIF(TRIM(customer_pet_name), '') AS customer_pet_name,
    NULLIF(TRIM(customer_pet_breed), '') AS customer_pet_breed,
    NULLIF(TRIM(pet_category), '') AS pet_category
FROM unified_source
WHERE TRY_CAST(sale_customer_id AS bigint) IS NOT NULL;

CREATE TABLE clickhouse.dwh.dim_product AS
WITH unified_source AS (
    SELECT
        CAST(id AS varchar) AS id,
        CAST(customer_first_name AS varchar) AS customer_first_name,
        CAST(customer_last_name AS varchar) AS customer_last_name,
        CAST(customer_age AS varchar) AS customer_age,
        CAST(customer_email AS varchar) AS customer_email,
        CAST(customer_country AS varchar) AS customer_country,
        CAST(customer_postal_code AS varchar) AS customer_postal_code,
        CAST(customer_pet_type AS varchar) AS customer_pet_type,
        CAST(customer_pet_name AS varchar) AS customer_pet_name,
        CAST(customer_pet_breed AS varchar) AS customer_pet_breed,
        CAST(seller_first_name AS varchar) AS seller_first_name,
        CAST(seller_last_name AS varchar) AS seller_last_name,
        CAST(seller_email AS varchar) AS seller_email,
        CAST(seller_country AS varchar) AS seller_country,
        CAST(seller_postal_code AS varchar) AS seller_postal_code,
        CAST(product_name AS varchar) AS product_name,
        CAST(product_category AS varchar) AS product_category,
        CAST(product_price AS varchar) AS product_price,
        CAST(product_quantity AS varchar) AS product_quantity,
        CAST(sale_date AS varchar) AS sale_date,
        CAST(sale_customer_id AS varchar) AS sale_customer_id,
        CAST(sale_seller_id AS varchar) AS sale_seller_id,
        CAST(sale_product_id AS varchar) AS sale_product_id,
        CAST(sale_quantity AS varchar) AS sale_quantity,
        CAST(sale_total_price AS varchar) AS sale_total_price,
        CAST(store_name AS varchar) AS store_name,
        CAST(store_location AS varchar) AS store_location,
        CAST(store_city AS varchar) AS store_city,
        CAST(store_state AS varchar) AS store_state,
        CAST(store_country AS varchar) AS store_country,
        CAST(store_phone AS varchar) AS store_phone,
        CAST(store_email AS varchar) AS store_email,
        CAST(pet_category AS varchar) AS pet_category,
        CAST(product_weight AS varchar) AS product_weight,
        CAST(product_color AS varchar) AS product_color,
        CAST(product_size AS varchar) AS product_size,
        CAST(product_brand AS varchar) AS product_brand,
        CAST(product_material AS varchar) AS product_material,
        CAST(product_description AS varchar) AS product_description,
        CAST(product_rating AS varchar) AS product_rating,
        CAST(product_reviews AS varchar) AS product_reviews,
        CAST(product_release_date AS varchar) AS product_release_date,
        CAST(product_expiry_date AS varchar) AS product_expiry_date,
        CAST(supplier_name AS varchar) AS supplier_name,
        CAST(supplier_contact AS varchar) AS supplier_contact,
        CAST(supplier_email AS varchar) AS supplier_email,
        CAST(supplier_phone AS varchar) AS supplier_phone,
        CAST(supplier_address AS varchar) AS supplier_address,
        CAST(supplier_city AS varchar) AS supplier_city,
        CAST(supplier_country AS varchar) AS supplier_country
    FROM postgres.raw.mock_data
    UNION ALL
    SELECT
        CAST(id AS varchar) AS id,
        CAST(customer_first_name AS varchar) AS customer_first_name,
        CAST(customer_last_name AS varchar) AS customer_last_name,
        CAST(customer_age AS varchar) AS customer_age,
        CAST(customer_email AS varchar) AS customer_email,
        CAST(customer_country AS varchar) AS customer_country,
        CAST(customer_postal_code AS varchar) AS customer_postal_code,
        CAST(customer_pet_type AS varchar) AS customer_pet_type,
        CAST(customer_pet_name AS varchar) AS customer_pet_name,
        CAST(customer_pet_breed AS varchar) AS customer_pet_breed,
        CAST(seller_first_name AS varchar) AS seller_first_name,
        CAST(seller_last_name AS varchar) AS seller_last_name,
        CAST(seller_email AS varchar) AS seller_email,
        CAST(seller_country AS varchar) AS seller_country,
        CAST(seller_postal_code AS varchar) AS seller_postal_code,
        CAST(product_name AS varchar) AS product_name,
        CAST(product_category AS varchar) AS product_category,
        CAST(product_price AS varchar) AS product_price,
        CAST(product_quantity AS varchar) AS product_quantity,
        CAST(sale_date AS varchar) AS sale_date,
        CAST(sale_customer_id AS varchar) AS sale_customer_id,
        CAST(sale_seller_id AS varchar) AS sale_seller_id,
        CAST(sale_product_id AS varchar) AS sale_product_id,
        CAST(sale_quantity AS varchar) AS sale_quantity,
        CAST(sale_total_price AS varchar) AS sale_total_price,
        CAST(store_name AS varchar) AS store_name,
        CAST(store_location AS varchar) AS store_location,
        CAST(store_city AS varchar) AS store_city,
        CAST(store_state AS varchar) AS store_state,
        CAST(store_country AS varchar) AS store_country,
        CAST(store_phone AS varchar) AS store_phone,
        CAST(store_email AS varchar) AS store_email,
        CAST(pet_category AS varchar) AS pet_category,
        CAST(product_weight AS varchar) AS product_weight,
        CAST(product_color AS varchar) AS product_color,
        CAST(product_size AS varchar) AS product_size,
        CAST(product_brand AS varchar) AS product_brand,
        CAST(product_material AS varchar) AS product_material,
        CAST(product_description AS varchar) AS product_description,
        CAST(product_rating AS varchar) AS product_rating,
        CAST(product_reviews AS varchar) AS product_reviews,
        CAST(product_release_date AS varchar) AS product_release_date,
        CAST(product_expiry_date AS varchar) AS product_expiry_date,
        CAST(supplier_name AS varchar) AS supplier_name,
        CAST(supplier_contact AS varchar) AS supplier_contact,
        CAST(supplier_email AS varchar) AS supplier_email,
        CAST(supplier_phone AS varchar) AS supplier_phone,
        CAST(supplier_address AS varchar) AS supplier_address,
        CAST(supplier_city AS varchar) AS supplier_city,
        CAST(supplier_country AS varchar) AS supplier_country
    FROM clickhouse.raw.mock_data
)
SELECT DISTINCT
    TRY_CAST(sale_product_id AS bigint) AS product_id,
    NULLIF(TRIM(product_name), '') AS product_name,
    NULLIF(TRIM(product_category), '') AS product_category,
    TRY_CAST(product_price AS double) AS product_price,
    TRY_CAST(product_quantity AS integer) AS product_quantity,
    TRY_CAST(product_weight AS double) AS product_weight,
    NULLIF(TRIM(product_color), '') AS product_color,
    NULLIF(TRIM(product_size), '') AS product_size,
    NULLIF(TRIM(product_brand), '') AS product_brand,
    NULLIF(TRIM(product_material), '') AS product_material,
    NULLIF(TRIM(product_description), '') AS product_description,
    TRY_CAST(product_rating AS double) AS product_rating,
    TRY_CAST(product_reviews AS integer) AS product_reviews,
    TRY(CAST(date_parse(product_release_date, '%c/%e/%Y') AS date)) AS product_release_date,
    TRY(CAST(date_parse(product_expiry_date, '%c/%e/%Y') AS date)) AS product_expiry_date
FROM unified_source
WHERE TRY_CAST(sale_product_id AS bigint) IS NOT NULL;

CREATE TABLE clickhouse.dwh.dim_store AS
WITH unified_source AS (
    SELECT
        CAST(id AS varchar) AS id,
        CAST(customer_first_name AS varchar) AS customer_first_name,
        CAST(customer_last_name AS varchar) AS customer_last_name,
        CAST(customer_age AS varchar) AS customer_age,
        CAST(customer_email AS varchar) AS customer_email,
        CAST(customer_country AS varchar) AS customer_country,
        CAST(customer_postal_code AS varchar) AS customer_postal_code,
        CAST(customer_pet_type AS varchar) AS customer_pet_type,
        CAST(customer_pet_name AS varchar) AS customer_pet_name,
        CAST(customer_pet_breed AS varchar) AS customer_pet_breed,
        CAST(seller_first_name AS varchar) AS seller_first_name,
        CAST(seller_last_name AS varchar) AS seller_last_name,
        CAST(seller_email AS varchar) AS seller_email,
        CAST(seller_country AS varchar) AS seller_country,
        CAST(seller_postal_code AS varchar) AS seller_postal_code,
        CAST(product_name AS varchar) AS product_name,
        CAST(product_category AS varchar) AS product_category,
        CAST(product_price AS varchar) AS product_price,
        CAST(product_quantity AS varchar) AS product_quantity,
        CAST(sale_date AS varchar) AS sale_date,
        CAST(sale_customer_id AS varchar) AS sale_customer_id,
        CAST(sale_seller_id AS varchar) AS sale_seller_id,
        CAST(sale_product_id AS varchar) AS sale_product_id,
        CAST(sale_quantity AS varchar) AS sale_quantity,
        CAST(sale_total_price AS varchar) AS sale_total_price,
        CAST(store_name AS varchar) AS store_name,
        CAST(store_location AS varchar) AS store_location,
        CAST(store_city AS varchar) AS store_city,
        CAST(store_state AS varchar) AS store_state,
        CAST(store_country AS varchar) AS store_country,
        CAST(store_phone AS varchar) AS store_phone,
        CAST(store_email AS varchar) AS store_email,
        CAST(pet_category AS varchar) AS pet_category,
        CAST(product_weight AS varchar) AS product_weight,
        CAST(product_color AS varchar) AS product_color,
        CAST(product_size AS varchar) AS product_size,
        CAST(product_brand AS varchar) AS product_brand,
        CAST(product_material AS varchar) AS product_material,
        CAST(product_description AS varchar) AS product_description,
        CAST(product_rating AS varchar) AS product_rating,
        CAST(product_reviews AS varchar) AS product_reviews,
        CAST(product_release_date AS varchar) AS product_release_date,
        CAST(product_expiry_date AS varchar) AS product_expiry_date,
        CAST(supplier_name AS varchar) AS supplier_name,
        CAST(supplier_contact AS varchar) AS supplier_contact,
        CAST(supplier_email AS varchar) AS supplier_email,
        CAST(supplier_phone AS varchar) AS supplier_phone,
        CAST(supplier_address AS varchar) AS supplier_address,
        CAST(supplier_city AS varchar) AS supplier_city,
        CAST(supplier_country AS varchar) AS supplier_country
    FROM postgres.raw.mock_data
    UNION ALL
    SELECT
        CAST(id AS varchar) AS id,
        CAST(customer_first_name AS varchar) AS customer_first_name,
        CAST(customer_last_name AS varchar) AS customer_last_name,
        CAST(customer_age AS varchar) AS customer_age,
        CAST(customer_email AS varchar) AS customer_email,
        CAST(customer_country AS varchar) AS customer_country,
        CAST(customer_postal_code AS varchar) AS customer_postal_code,
        CAST(customer_pet_type AS varchar) AS customer_pet_type,
        CAST(customer_pet_name AS varchar) AS customer_pet_name,
        CAST(customer_pet_breed AS varchar) AS customer_pet_breed,
        CAST(seller_first_name AS varchar) AS seller_first_name,
        CAST(seller_last_name AS varchar) AS seller_last_name,
        CAST(seller_email AS varchar) AS seller_email,
        CAST(seller_country AS varchar) AS seller_country,
        CAST(seller_postal_code AS varchar) AS seller_postal_code,
        CAST(product_name AS varchar) AS product_name,
        CAST(product_category AS varchar) AS product_category,
        CAST(product_price AS varchar) AS product_price,
        CAST(product_quantity AS varchar) AS product_quantity,
        CAST(sale_date AS varchar) AS sale_date,
        CAST(sale_customer_id AS varchar) AS sale_customer_id,
        CAST(sale_seller_id AS varchar) AS sale_seller_id,
        CAST(sale_product_id AS varchar) AS sale_product_id,
        CAST(sale_quantity AS varchar) AS sale_quantity,
        CAST(sale_total_price AS varchar) AS sale_total_price,
        CAST(store_name AS varchar) AS store_name,
        CAST(store_location AS varchar) AS store_location,
        CAST(store_city AS varchar) AS store_city,
        CAST(store_state AS varchar) AS store_state,
        CAST(store_country AS varchar) AS store_country,
        CAST(store_phone AS varchar) AS store_phone,
        CAST(store_email AS varchar) AS store_email,
        CAST(pet_category AS varchar) AS pet_category,
        CAST(product_weight AS varchar) AS product_weight,
        CAST(product_color AS varchar) AS product_color,
        CAST(product_size AS varchar) AS product_size,
        CAST(product_brand AS varchar) AS product_brand,
        CAST(product_material AS varchar) AS product_material,
        CAST(product_description AS varchar) AS product_description,
        CAST(product_rating AS varchar) AS product_rating,
        CAST(product_reviews AS varchar) AS product_reviews,
        CAST(product_release_date AS varchar) AS product_release_date,
        CAST(product_expiry_date AS varchar) AS product_expiry_date,
        CAST(supplier_name AS varchar) AS supplier_name,
        CAST(supplier_contact AS varchar) AS supplier_contact,
        CAST(supplier_email AS varchar) AS supplier_email,
        CAST(supplier_phone AS varchar) AS supplier_phone,
        CAST(supplier_address AS varchar) AS supplier_address,
        CAST(supplier_city AS varchar) AS supplier_city,
        CAST(supplier_country AS varchar) AS supplier_country
    FROM clickhouse.raw.mock_data
),
stores AS (
    SELECT DISTINCT
        NULLIF(TRIM(store_name), '') AS store_name,
        NULLIF(TRIM(store_location), '') AS store_location,
        NULLIF(TRIM(store_city), '') AS store_city,
        NULLIF(TRIM(store_state), '') AS store_state,
        NULLIF(TRIM(store_country), '') AS store_country,
        NULLIF(TRIM(store_phone), '') AS store_phone,
        NULLIF(TRIM(store_email), '') AS store_email
    FROM unified_source
)
SELECT
    ROW_NUMBER() OVER (ORDER BY store_name, store_email, store_phone) AS store_id,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email
FROM stores;

CREATE TABLE clickhouse.dwh.dim_supplier AS
WITH unified_source AS (
    SELECT
        CAST(id AS varchar) AS id,
        CAST(customer_first_name AS varchar) AS customer_first_name,
        CAST(customer_last_name AS varchar) AS customer_last_name,
        CAST(customer_age AS varchar) AS customer_age,
        CAST(customer_email AS varchar) AS customer_email,
        CAST(customer_country AS varchar) AS customer_country,
        CAST(customer_postal_code AS varchar) AS customer_postal_code,
        CAST(customer_pet_type AS varchar) AS customer_pet_type,
        CAST(customer_pet_name AS varchar) AS customer_pet_name,
        CAST(customer_pet_breed AS varchar) AS customer_pet_breed,
        CAST(seller_first_name AS varchar) AS seller_first_name,
        CAST(seller_last_name AS varchar) AS seller_last_name,
        CAST(seller_email AS varchar) AS seller_email,
        CAST(seller_country AS varchar) AS seller_country,
        CAST(seller_postal_code AS varchar) AS seller_postal_code,
        CAST(product_name AS varchar) AS product_name,
        CAST(product_category AS varchar) AS product_category,
        CAST(product_price AS varchar) AS product_price,
        CAST(product_quantity AS varchar) AS product_quantity,
        CAST(sale_date AS varchar) AS sale_date,
        CAST(sale_customer_id AS varchar) AS sale_customer_id,
        CAST(sale_seller_id AS varchar) AS sale_seller_id,
        CAST(sale_product_id AS varchar) AS sale_product_id,
        CAST(sale_quantity AS varchar) AS sale_quantity,
        CAST(sale_total_price AS varchar) AS sale_total_price,
        CAST(store_name AS varchar) AS store_name,
        CAST(store_location AS varchar) AS store_location,
        CAST(store_city AS varchar) AS store_city,
        CAST(store_state AS varchar) AS store_state,
        CAST(store_country AS varchar) AS store_country,
        CAST(store_phone AS varchar) AS store_phone,
        CAST(store_email AS varchar) AS store_email,
        CAST(pet_category AS varchar) AS pet_category,
        CAST(product_weight AS varchar) AS product_weight,
        CAST(product_color AS varchar) AS product_color,
        CAST(product_size AS varchar) AS product_size,
        CAST(product_brand AS varchar) AS product_brand,
        CAST(product_material AS varchar) AS product_material,
        CAST(product_description AS varchar) AS product_description,
        CAST(product_rating AS varchar) AS product_rating,
        CAST(product_reviews AS varchar) AS product_reviews,
        CAST(product_release_date AS varchar) AS product_release_date,
        CAST(product_expiry_date AS varchar) AS product_expiry_date,
        CAST(supplier_name AS varchar) AS supplier_name,
        CAST(supplier_contact AS varchar) AS supplier_contact,
        CAST(supplier_email AS varchar) AS supplier_email,
        CAST(supplier_phone AS varchar) AS supplier_phone,
        CAST(supplier_address AS varchar) AS supplier_address,
        CAST(supplier_city AS varchar) AS supplier_city,
        CAST(supplier_country AS varchar) AS supplier_country
    FROM postgres.raw.mock_data
    UNION ALL
    SELECT
        CAST(id AS varchar) AS id,
        CAST(customer_first_name AS varchar) AS customer_first_name,
        CAST(customer_last_name AS varchar) AS customer_last_name,
        CAST(customer_age AS varchar) AS customer_age,
        CAST(customer_email AS varchar) AS customer_email,
        CAST(customer_country AS varchar) AS customer_country,
        CAST(customer_postal_code AS varchar) AS customer_postal_code,
        CAST(customer_pet_type AS varchar) AS customer_pet_type,
        CAST(customer_pet_name AS varchar) AS customer_pet_name,
        CAST(customer_pet_breed AS varchar) AS customer_pet_breed,
        CAST(seller_first_name AS varchar) AS seller_first_name,
        CAST(seller_last_name AS varchar) AS seller_last_name,
        CAST(seller_email AS varchar) AS seller_email,
        CAST(seller_country AS varchar) AS seller_country,
        CAST(seller_postal_code AS varchar) AS seller_postal_code,
        CAST(product_name AS varchar) AS product_name,
        CAST(product_category AS varchar) AS product_category,
        CAST(product_price AS varchar) AS product_price,
        CAST(product_quantity AS varchar) AS product_quantity,
        CAST(sale_date AS varchar) AS sale_date,
        CAST(sale_customer_id AS varchar) AS sale_customer_id,
        CAST(sale_seller_id AS varchar) AS sale_seller_id,
        CAST(sale_product_id AS varchar) AS sale_product_id,
        CAST(sale_quantity AS varchar) AS sale_quantity,
        CAST(sale_total_price AS varchar) AS sale_total_price,
        CAST(store_name AS varchar) AS store_name,
        CAST(store_location AS varchar) AS store_location,
        CAST(store_city AS varchar) AS store_city,
        CAST(store_state AS varchar) AS store_state,
        CAST(store_country AS varchar) AS store_country,
        CAST(store_phone AS varchar) AS store_phone,
        CAST(store_email AS varchar) AS store_email,
        CAST(pet_category AS varchar) AS pet_category,
        CAST(product_weight AS varchar) AS product_weight,
        CAST(product_color AS varchar) AS product_color,
        CAST(product_size AS varchar) AS product_size,
        CAST(product_brand AS varchar) AS product_brand,
        CAST(product_material AS varchar) AS product_material,
        CAST(product_description AS varchar) AS product_description,
        CAST(product_rating AS varchar) AS product_rating,
        CAST(product_reviews AS varchar) AS product_reviews,
        CAST(product_release_date AS varchar) AS product_release_date,
        CAST(product_expiry_date AS varchar) AS product_expiry_date,
        CAST(supplier_name AS varchar) AS supplier_name,
        CAST(supplier_contact AS varchar) AS supplier_contact,
        CAST(supplier_email AS varchar) AS supplier_email,
        CAST(supplier_phone AS varchar) AS supplier_phone,
        CAST(supplier_address AS varchar) AS supplier_address,
        CAST(supplier_city AS varchar) AS supplier_city,
        CAST(supplier_country AS varchar) AS supplier_country
    FROM clickhouse.raw.mock_data
),
suppliers AS (
    SELECT DISTINCT
        NULLIF(TRIM(supplier_name), '') AS supplier_name,
        NULLIF(TRIM(supplier_contact), '') AS supplier_contact,
        NULLIF(TRIM(supplier_email), '') AS supplier_email,
        NULLIF(TRIM(supplier_phone), '') AS supplier_phone,
        NULLIF(TRIM(supplier_address), '') AS supplier_address,
        NULLIF(TRIM(supplier_city), '') AS supplier_city,
        NULLIF(TRIM(supplier_country), '') AS supplier_country
    FROM unified_source
)
SELECT
    ROW_NUMBER() OVER (ORDER BY supplier_name, supplier_email, supplier_phone) AS supplier_id,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM suppliers;

CREATE TABLE clickhouse.dwh.fact_sales AS
WITH unified_source AS (
    SELECT
        CAST(id AS varchar) AS id,
        CAST(customer_first_name AS varchar) AS customer_first_name,
        CAST(customer_last_name AS varchar) AS customer_last_name,
        CAST(customer_age AS varchar) AS customer_age,
        CAST(customer_email AS varchar) AS customer_email,
        CAST(customer_country AS varchar) AS customer_country,
        CAST(customer_postal_code AS varchar) AS customer_postal_code,
        CAST(customer_pet_type AS varchar) AS customer_pet_type,
        CAST(customer_pet_name AS varchar) AS customer_pet_name,
        CAST(customer_pet_breed AS varchar) AS customer_pet_breed,
        CAST(seller_first_name AS varchar) AS seller_first_name,
        CAST(seller_last_name AS varchar) AS seller_last_name,
        CAST(seller_email AS varchar) AS seller_email,
        CAST(seller_country AS varchar) AS seller_country,
        CAST(seller_postal_code AS varchar) AS seller_postal_code,
        CAST(product_name AS varchar) AS product_name,
        CAST(product_category AS varchar) AS product_category,
        CAST(product_price AS varchar) AS product_price,
        CAST(product_quantity AS varchar) AS product_quantity,
        CAST(sale_date AS varchar) AS sale_date,
        CAST(sale_customer_id AS varchar) AS sale_customer_id,
        CAST(sale_seller_id AS varchar) AS sale_seller_id,
        CAST(sale_product_id AS varchar) AS sale_product_id,
        CAST(sale_quantity AS varchar) AS sale_quantity,
        CAST(sale_total_price AS varchar) AS sale_total_price,
        CAST(store_name AS varchar) AS store_name,
        CAST(store_location AS varchar) AS store_location,
        CAST(store_city AS varchar) AS store_city,
        CAST(store_state AS varchar) AS store_state,
        CAST(store_country AS varchar) AS store_country,
        CAST(store_phone AS varchar) AS store_phone,
        CAST(store_email AS varchar) AS store_email,
        CAST(pet_category AS varchar) AS pet_category,
        CAST(product_weight AS varchar) AS product_weight,
        CAST(product_color AS varchar) AS product_color,
        CAST(product_size AS varchar) AS product_size,
        CAST(product_brand AS varchar) AS product_brand,
        CAST(product_material AS varchar) AS product_material,
        CAST(product_description AS varchar) AS product_description,
        CAST(product_rating AS varchar) AS product_rating,
        CAST(product_reviews AS varchar) AS product_reviews,
        CAST(product_release_date AS varchar) AS product_release_date,
        CAST(product_expiry_date AS varchar) AS product_expiry_date,
        CAST(supplier_name AS varchar) AS supplier_name,
        CAST(supplier_contact AS varchar) AS supplier_contact,
        CAST(supplier_email AS varchar) AS supplier_email,
        CAST(supplier_phone AS varchar) AS supplier_phone,
        CAST(supplier_address AS varchar) AS supplier_address,
        CAST(supplier_city AS varchar) AS supplier_city,
        CAST(supplier_country AS varchar) AS supplier_country
    FROM postgres.raw.mock_data
    UNION ALL
    SELECT
        CAST(id AS varchar) AS id,
        CAST(customer_first_name AS varchar) AS customer_first_name,
        CAST(customer_last_name AS varchar) AS customer_last_name,
        CAST(customer_age AS varchar) AS customer_age,
        CAST(customer_email AS varchar) AS customer_email,
        CAST(customer_country AS varchar) AS customer_country,
        CAST(customer_postal_code AS varchar) AS customer_postal_code,
        CAST(customer_pet_type AS varchar) AS customer_pet_type,
        CAST(customer_pet_name AS varchar) AS customer_pet_name,
        CAST(customer_pet_breed AS varchar) AS customer_pet_breed,
        CAST(seller_first_name AS varchar) AS seller_first_name,
        CAST(seller_last_name AS varchar) AS seller_last_name,
        CAST(seller_email AS varchar) AS seller_email,
        CAST(seller_country AS varchar) AS seller_country,
        CAST(seller_postal_code AS varchar) AS seller_postal_code,
        CAST(product_name AS varchar) AS product_name,
        CAST(product_category AS varchar) AS product_category,
        CAST(product_price AS varchar) AS product_price,
        CAST(product_quantity AS varchar) AS product_quantity,
        CAST(sale_date AS varchar) AS sale_date,
        CAST(sale_customer_id AS varchar) AS sale_customer_id,
        CAST(sale_seller_id AS varchar) AS sale_seller_id,
        CAST(sale_product_id AS varchar) AS sale_product_id,
        CAST(sale_quantity AS varchar) AS sale_quantity,
        CAST(sale_total_price AS varchar) AS sale_total_price,
        CAST(store_name AS varchar) AS store_name,
        CAST(store_location AS varchar) AS store_location,
        CAST(store_city AS varchar) AS store_city,
        CAST(store_state AS varchar) AS store_state,
        CAST(store_country AS varchar) AS store_country,
        CAST(store_phone AS varchar) AS store_phone,
        CAST(store_email AS varchar) AS store_email,
        CAST(pet_category AS varchar) AS pet_category,
        CAST(product_weight AS varchar) AS product_weight,
        CAST(product_color AS varchar) AS product_color,
        CAST(product_size AS varchar) AS product_size,
        CAST(product_brand AS varchar) AS product_brand,
        CAST(product_material AS varchar) AS product_material,
        CAST(product_description AS varchar) AS product_description,
        CAST(product_rating AS varchar) AS product_rating,
        CAST(product_reviews AS varchar) AS product_reviews,
        CAST(product_release_date AS varchar) AS product_release_date,
        CAST(product_expiry_date AS varchar) AS product_expiry_date,
        CAST(supplier_name AS varchar) AS supplier_name,
        CAST(supplier_contact AS varchar) AS supplier_contact,
        CAST(supplier_email AS varchar) AS supplier_email,
        CAST(supplier_phone AS varchar) AS supplier_phone,
        CAST(supplier_address AS varchar) AS supplier_address,
        CAST(supplier_city AS varchar) AS supplier_city,
        CAST(supplier_country AS varchar) AS supplier_country
    FROM clickhouse.raw.mock_data
),
store_map AS (
    SELECT
        store_id,
        store_name,
        store_location,
        store_city,
        store_state,
        store_country,
        store_phone,
        store_email
    FROM clickhouse.dwh.dim_store
),
supplier_map AS (
    SELECT
        supplier_id,
        supplier_name,
        supplier_contact,
        supplier_email,
        supplier_phone,
        supplier_address,
        supplier_city,
        supplier_country
    FROM clickhouse.dwh.dim_supplier
)
SELECT
    TRY_CAST(s.id AS bigint) AS fact_id,
    TRY_CAST(s.id AS bigint) AS order_id,
    CAST(date_format(TRY(CAST(date_parse(s.sale_date, '%c/%e/%Y') AS date)), '%Y%m%d') AS bigint) AS date_id,
    TRY_CAST(s.sale_customer_id AS bigint) AS customer_id,
    TRY_CAST(s.sale_product_id AS bigint) AS product_id,
    sm.store_id AS store_id,
    sup.supplier_id AS supplier_id,
    TRY_CAST(s.sale_seller_id AS bigint) AS seller_id,
    NULLIF(TRIM(s.seller_first_name), '') AS seller_first_name,
    NULLIF(TRIM(s.seller_last_name), '') AS seller_last_name,
    NULLIF(TRIM(s.seller_email), '') AS seller_email,
    NULLIF(TRIM(s.seller_country), '') AS seller_country,
    TRY_CAST(s.sale_quantity AS integer) AS sale_quantity,
    TRY_CAST(s.product_price AS double) AS unit_price,
    TRY_CAST(s.sale_total_price AS double) AS sale_total_price
FROM unified_source s
LEFT JOIN store_map sm
    ON COALESCE(NULLIF(TRIM(s.store_name), ''), '') = COALESCE(sm.store_name, '')
   AND COALESCE(NULLIF(TRIM(s.store_email), ''), '') = COALESCE(sm.store_email, '')
   AND COALESCE(NULLIF(TRIM(s.store_phone), ''), '') = COALESCE(sm.store_phone, '')
LEFT JOIN supplier_map sup
    ON COALESCE(NULLIF(TRIM(s.supplier_name), ''), '') = COALESCE(sup.supplier_name, '')
   AND COALESCE(NULLIF(TRIM(s.supplier_email), ''), '') = COALESCE(sup.supplier_email, '')
   AND COALESCE(NULLIF(TRIM(s.supplier_phone), ''), '') = COALESCE(sup.supplier_phone, '')
WHERE TRY_CAST(s.id AS bigint) IS NOT NULL;
