CREATE DATABASE IF NOT EXISTS raw;
CREATE DATABASE IF NOT EXISTS dwh;
CREATE DATABASE IF NOT EXISTS report;

CREATE TABLE IF NOT EXISTS raw.mock_data (
    id Nullable(String),
    customer_first_name Nullable(String),
    customer_last_name Nullable(String),
    customer_age Nullable(String),
    customer_email Nullable(String),
    customer_country Nullable(String),
    customer_postal_code Nullable(String),
    customer_pet_type Nullable(String),
    customer_pet_name Nullable(String),
    customer_pet_breed Nullable(String),
    seller_first_name Nullable(String),
    seller_last_name Nullable(String),
    seller_email Nullable(String),
    seller_country Nullable(String),
    seller_postal_code Nullable(String),
    product_name Nullable(String),
    product_category Nullable(String),
    product_price Nullable(String),
    product_quantity Nullable(String),
    sale_date Nullable(String),
    sale_customer_id Nullable(String),
    sale_seller_id Nullable(String),
    sale_product_id Nullable(String),
    sale_quantity Nullable(String),
    sale_total_price Nullable(String),
    store_name Nullable(String),
    store_location Nullable(String),
    store_city Nullable(String),
    store_state Nullable(String),
    store_country Nullable(String),
    store_phone Nullable(String),
    store_email Nullable(String),
    pet_category Nullable(String),
    product_weight Nullable(String),
    product_color Nullable(String),
    product_size Nullable(String),
    product_brand Nullable(String),
    product_material Nullable(String),
    product_description Nullable(String),
    product_rating Nullable(String),
    product_reviews Nullable(String),
    product_release_date Nullable(String),
    product_expiry_date Nullable(String),
    supplier_name Nullable(String),
    supplier_contact Nullable(String),
    supplier_email Nullable(String),
    supplier_phone Nullable(String),
    supplier_address Nullable(String),
    supplier_city Nullable(String),
    supplier_country Nullable(String)
)
ENGINE = MergeTree
ORDER BY tuple();
